"""ZipperGen — formal multi-agent LLM coordination programs."""

from zippergen.syntax import *          # noqa: F401, F403
from zippergen.actions import *         # noqa: F401, F403
from zippergen.backends import *        # noqa: F401, F403
from zippergen.human_backends import *  # noqa: F401, F403
from zippergen.assistant_backends import *  # noqa: F401, F403
from zippergen.formula import *         # noqa: F401, F403
from zippergen.builder import *         # noqa: F401, F403
from zippergen.projection import *      # noqa: F401, F403
from zippergen.runtime import *         # noqa: F401, F403
from zippergen.sqlite_runner import *   # noqa: F401, F403
from zippergen.deployment import *      # noqa: F401, F403
from zippergen.connectors import *      # noqa: F401, F403
from zippergen.view import *            # noqa: F401, F403
from zippergen.semantic import *        # noqa: F401, F403
from zippergen.google_sheets import *    # noqa: F401, F403
from zippergen.google_gmail import *     # noqa: F401, F403

# This list is deliberately explicit. Adding a name to a module's ``__all__``
# must not silently expand the package-level public surface.
__all__: list[str] = [
    # Syntax and intermediate representation.
    "ZType",
    "Json",
    "is_ztype",
    "is_json_value",
    "validate_zvalue",
    "Lifeline",
    "Var",
    "Expr",
    "VarExpr",
    "LitExpr",
    "LLMAction",
    "PureAction",
    "EffectAction",
    "AssistantAction",
    "PlannerAction",
    "HumanAction",
    "ZTypeAtLifeline",
    "Stmt",
    "EmptyStmt",
    "MsgStmt",
    "CoregionStmt",
    "ActStmt",
    "SkipStmt",
    "SeqStmt",
    "IfStmt",
    "WhileStmt",
    "ParallelStmt",
    "LocalStmt",
    "AnyStmt",
    "SendStmt",
    "RecvStmt",
    "ReceiveAnyStmt",
    "SelfAssignStmt",
    "IfRecvStmt",
    "WhileRecvStmt",
    "ParallelLocalStmt",
    "Workflow",
    "make_kappa_ctrl",
    "is_kappa_ctrl",
    "canonical_construct_key",
    "seq",
    "participation_set",
    "pp",
    # Actions and backends.
    "llm",
    "pure",
    "effect",
    "assistant",
    "planner",
    "human",
    "ManagedBackend",
    "backend_from_spec",
    "make_mistral_backend",
    "make_openai_backend",
    "make_anthropic_backend",
    "make_lifeline_router",
    "PROVIDER_API_KEY_VARIABLES",
    "make_scripted_backend",
    "load_scripted_script",
    "validate_local_idle_policies",
    "router_from_specs",
    "make_cli_human_backend",
    "make_sqlite_human_backend",
    "AssistantExecutionError",
    "make_cli_assistant_backend",
    # Causal-past formulas.
    "EventContext",
    "Formula",
    "AtomicFormula",
    "OnFormula",
    "YFormula",
    "AtFormula",
    "SinceFormula",
    "PastFormula",
    "ConstFormula",
    "AndFormula",
    "OrFormula",
    "NotFormula",
    "FieldTerm",
    "AnyFormula",
    "atom",
    "At",
    "Here",
    "Y",
    "Prev",
    "on",
    "since",
    "P",
    "true",
    "false",
    "subformulas",
    # Workflow construction, projection, and execution.
    "workflow",
    "fragment",
    "msg",
    "act",
    "skip",
    "coregion",
    "parallel",
    "branch",
    "if_",
    "while_",
    "project",
    "run",
    "mock_llm",
    "console_trace",
    "tee_traces",
    "LocalSupervisor",
    "run_sqlite",
    # Deployment and connectors.
    "DeploymentField",
    "DeploymentPackage",
    "DeploymentSetup",
    "DeploymentSpec",
    "deployment_spec_from_module",
    "normalize_deployment_spec",
    "ConnectorRequirement",
    "connector_requirements_from_module",
    "GOOGLE_SHEETS_SCOPE",
    "GoogleSheetsError",
    "GoogleSheetsTable",
    "authorize_google_sheets",
    "check_google_authorization",
    "read_json_rows",
    "upsert_json_row",
    "GmailError",
    "GmailMailbox",
    # Views and semantic comparison.
    "DETAILS",
    "ViewOptions",
    "render_workflow",
    "render_workflow_json",
    "workflow_view_data",
    "SEMANTIC_SNAPSHOT_SCHEMA",
    "read_semantic_snapshot",
    "render_semantic_diff",
    "semantic_diff",
    "semantic_diff_models",
    "semantic_snapshot",
    "workflow_semantics",
]
